python_bootstrap_binary(
    name = "nix_wrapper",
    main = "nix_wrapper.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "record_nix_path",
    main = "record_nix_path.py",
    visibility = ["PUBLIC"],
)
